language: r
sudo: false
cache: packages

matrix:
  include:
    - os: linux
    - os: osx

warnings_are_errors: true

notifications:
  email:
    recipients:
      - dbt1@williams.edu
    on_success: always
    on_failure: always

branches:
  only:
    - devel

latex: false  # Work around tlmgr issues.

install:
  - Rscript --vanilla -e 'install.packages("coda", dependencies = TRUE, repos = "http://cran.us.r-project.org")'
  - Rscript --vanilla -e 'install.packages("dplyr", dependencies = TRUE, repos = "http://cran.us.r-project.org")'
  - Rscript --vanilla -e 'install.packages("nimble", dependencies = TRUE, repos = "http://cran.us.r-project.org")'
  - Rscript --vanilla -e 'install.packages("reshape2", dependencies = TRUE, repos = "http://cran.us.r-project.org")'
  - Rscript --vanilla -e 'install.packages("testthat", dependencies = TRUE, repos = "http://cran.us.r-project.org")'
  - Rscript --vanilla -e 'install.packages("tidyr", dependencies = TRUE, repos = "http://cran.us.r-project.org")'
  - R CMD INSTALL .

script:
  - Rscript --vanilla -e 'library(methods); library(nimbleEcology); library(testthat); test_package("nimbleEcology")'
